services:
  - type: web
    name: TubeTalk
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn routes:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: GEMINI_API_KEY
        sync: false
      - key: ASSEMBLYAI_API_KEY
        sync: false
      - key: YOUTUBE_COOKIES_CONTENT
        sync: false
    disk:
      name: data
      mountPath: /app/data
      sizeGB: 1